### ISSUE TITLE
Introduce RSL1 as installable mod

### ISSUE THREAD

**Issue by Rast1234** [rfg-modding/SyncFaction#20]
RSL1 and scripts made for it have value and deserve to be accessible.

## Things to do

* Locate most recent RSL1 distro and instructions
* Locate and test all the scripts and their instructions. Discord, FF, nexus, wherever
  * first person
  * EDF flyer
  * ???
  * mods that are already on FF. check all categories!
  * ask authors for permission to publish on FF

## Packaging

* Consider RSL1 as a separate dependency for scripts? Or bundle all existing scripts with it? _Have to see how it works/loads/applies if bundled together_
* RSL1 requires Steam version and disabling Reconstructor. Package it together with Steam Re-Enabler files or depend on it as a prerequisite? _Maybe second option as it's fool-proof_

**Comment by Rast1234** [comment]
from moneyl: 

https://discord.com/channels/416631942738346008/424009433253806080/1192943648690675913 flyer

https://discord.com/channels/416631942738346008/424009433253806080/1192944248102867125 telekinesis

**Comment by CamoRF** [comment]
[VehicleOverlay.zip](https://github.com/rfg-modding/SyncFaction/files/13883031/VehicleOverlay.zip)

**Comment by Rast1234** [comment]
tested some mods

* telekinesis: only works if auto-loaded, so it has to be named `main.lua`
* edf flyer: there is also a version with pitch/roll controls but flyer suddenly catches fire. i also managed to incorporate a teleport to vehicle keybind
* vehicle overlay: bugged but works with a minor tweak, had to move cleanup function call to the top

**Comment by Rast1234** [comment]
edf flyer script is useless without a mod to spawn it in safehouse. actual edf flyers that come at high alert levels are not controllable because there's still NPC piloting it.

so, need to include a modified safehouse vehicle mod to be able to spawn flyers, but mod should not be intrusive: not every player is going to use flyer script.

currently can hack this with an option in modinfo.xml which does not contain any <edit>s
