### ISSUE TITLE
Unexpected modinfo edit with no LIST_ACTION

### ISSUE THREAD

**Issue by Moneyl** [rfg-modding/SyncFaction#5]
Testing the old mortar pistol mod with the new MM features. The mod has <Edit> blocks for weapons.xtbl and explosions.xtbl. It has a LIST_ACTION for the weapons.xtbl edit but doesn't for explosions.xtbl. The weapons edit seems to be correct, but the explosions one differs from the behavior of the old MM. 

The old MM adds a new record on to the end of explosions.xtbl. 
SF modifies the first record. The mod still worked fine, but since it renamed the first record (mp_grenade in this case) it causes the grenades in MP to not explode. Since there's no explosion record called mp_grenade anymore.

I'm installing the mod on top of the Terraform Patch.

Here is the mod:
[MortarPistol.zip](https://github.com/rfg-modding/SyncFaction/files/12165856/MortarPistol.zip)

**Comment by Rast1234** [comment]
Turns out, MM treats "no value" as "LIST_ACTION:ADD" for top-level `<Edit>` nodes. For all other nodes, "no value" means other thing.
